# Generated by Django 5.2.4 on 2025-08-02 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('text1', models.TextField()),
                ('text2', models.TextField(blank=True)),
                ('text3', models.TextField(blank=True)),
                ('googlesite_url', models.URLField(blank=True, help_text='Google Site url')),
                ('slug', models.SlugField(blank=True, help_text='SEO Url Normalization', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Massage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the massage', max_digits=7)),
                ('duration', models.DurationField(help_text='Duration of the Massage (in HH:MM:SS format)')),
                ('text1', models.TextField()),
                ('text2', models.TextField(blank=True)),
                ('text3', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, help_text='SEO Url Normalization', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255)),
                ('address3', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.CharField(help_text='Postal code of the address', max_length=255)),
                ('city', models.CharField(help_text='City of the address', max_length=255)),
                ('country', models.CharField(help_text='Country of the address', max_length=255)),
                ('practice', models.OneToOneField(blank=True, default=False, on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='core.practice')),
            ],
            options={
                'verbose_name_plural': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='Openings',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('monday_open', models.TimeField(blank=True, help_text='Monday opening hour, HH:MM:SS', null=True)),
                ('monday_pause_start', models.TimeField(blank=True, help_text='Monday start of the Lunchbreak, HH:MM:SS', null=True)),
                ('monday_pause_end', models.TimeField(blank=True, help_text='Monday end of the Lunchbreak, HH:MM:SS', null=True)),
                ('monday_close', models.TimeField(blank=True, help_text='Monday closing hour, HH:MM:SS', null=True)),
                ('tuesday_open', models.TimeField(blank=True, help_text='Tuesday opening hour, HH:MM:SS', null=True)),
                ('tuesday_pause_start', models.TimeField(blank=True, help_text='Tuesday start of the Lunchbreak, HH:MM:SS', null=True)),
                ('tuesday_pause_end', models.TimeField(blank=True, help_text='Tuesday end of the Lunchbreak, HH:MM:SS', null=True)),
                ('tuesday_close', models.TimeField(blank=True, help_text='Tuesday closing hour, HH:MM:SS', null=True)),
                ('wednesday_open', models.TimeField(blank=True, help_text='Wednesday opening hour, HH:MM:SS', null=True)),
                ('wednesday_pause_start', models.TimeField(blank=True, help_text='Wednesday start of the Lunchbreak, HH:MM:SS', null=True)),
                ('wednesday_pause_end', models.TimeField(blank=True, help_text='Wednesday end of the Lunchbreak, HH:MM:SS', null=True)),
                ('wednesday_close', models.TimeField(blank=True, help_text='Wednesday closing hour, HH:MM:SS', null=True)),
                ('thursday_open', models.TimeField(blank=True, help_text='Thursday opening hour, HH:MM:SS', null=True)),
                ('thursday_pause_start', models.TimeField(blank=True, help_text='Thursday start of the Lunchbreak, HH:MM:SS', null=True)),
                ('thursday_pause_end', models.TimeField(blank=True, help_text='Thursday end of the Lunchbreak, HH:MM:SS', null=True)),
                ('thursday_close', models.TimeField(blank=True, help_text='Thursday closing hour, HH:MM:SS', null=True)),
                ('friday_open', models.TimeField(blank=True, help_text='Friday opening hour, HH:MM:SS', null=True)),
                ('friday_pause_start', models.TimeField(blank=True, help_text='Friday start of the Lunchbreak, HH:MM:SS', null=True)),
                ('friday_pause_end', models.TimeField(blank=True, help_text='Friday end of the Lunchbreak, HH:MM:SS', null=True)),
                ('friday_close', models.TimeField(blank=True, help_text='Friday closing hour, HH:MM:SS', null=True)),
                ('saturday_open', models.TimeField(blank=True, help_text='Saturday opening hour, HH:MM:SS', null=True)),
                ('saturday_pause_start', models.TimeField(blank=True, help_text='Saturday start of the Lunchbreak, HH:MM:SS', null=True)),
                ('saturday_pause_end', models.TimeField(blank=True, help_text='Saturday end of the Lunchbreak, HH:MM:SS', null=True)),
                ('saturday_close', models.TimeField(blank=True, help_text='Saturday closing hour, HH:MM:SS', null=True)),
                ('sunday_open', models.TimeField(blank=True, help_text='Sunday opening hour, HH:MM:SS', null=True)),
                ('sunday_pause_start', models.TimeField(blank=True, help_text='Sunday start of the Lunchbreak, HH:MM:SS', null=True)),
                ('sunday_pause_end', models.TimeField(blank=True, help_text='Sunday end of the Lunchbreak, HH:MM:SS', null=True)),
                ('sunday_close', models.TimeField(blank=True, help_text='Sunday closing hour, HH:MM:SS', null=True)),
                ('practice', models.OneToOneField(blank=True, default=False, on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='core.practice')),
            ],
            options={
                'verbose_name_plural': 'openings',
            },
        ),
        migrations.AddField(
            model_name='practice',
            name='massages',
            field=models.ManyToManyField(blank=True, default=False, to='core.massage'),
        ),
    ]
