# Generated by Django 5.2.4 on 2026-07-16 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='massage',
            name='calendlyURL',
        ),
    ]
