# Generated by Django 5.2.4 on 2026-08-25 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailuser',
            name='username',
        ),
    ]
