# Generated by Django 5.2.4 on 2025-08-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massage',
            name='slug',
            field=models.SlugField(help_text='SEO Url Normalization', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='practice',
            name='slug',
            field=models.SlugField(help_text='SEO Url Normalization', max_length=100, unique=True),
        ),
    ]
