# Generated by Django 5.2.4 on 2026-08-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_mailuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='mailuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='mailuser',
            name='activation_token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
