# Generated by Django 5.2.4 on 2025-08-02 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_massage_slug_alter_practice_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='practice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='core.practice'),
        ),
    ]
