# Generated by Django 5.2.4 on 2025-08-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_address_practice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='practice',
        ),
        migrations.RemoveField(
            model_name='openings',
            name='practice',
        ),
        migrations.AddField(
            model_name='address',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='openings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
