# Generated by Django 5.2.4 on 2026-08-27 15:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_mailuser_managers_mailuser_activation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailuser',
            name='activation_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
