# Generated by Django 5.2.4 on 2025-08-02 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_address_practice_remove_openings_practice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practice',
            name='massages',
        ),
    ]
