# Generated by Django 5.2.4 on 2025-08-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_practice_massages'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='massages',
            field=models.ManyToManyField(to='core.massage'),
        ),
    ]
