# Generated by Django 5.2.4 on 2025-08-02 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_practice_massages'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.address'),
        ),
        migrations.AddField(
            model_name='practice',
            name='opening',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.openings'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='massages',
            field=models.ManyToManyField(blank=True, to='core.massage'),
        ),
    ]
