# Generated by Django 5.2.4 on 2025-08-02 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_practice_address_practice_opening_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openings',
            name='monday_close',
            field=models.TimeField(blank=True, default=datetime.time(18, 0), help_text='Monday closing hour, HH:MM:SS', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='monday_open',
            field=models.TimeField(blank=True, default=datetime.time(10, 0), help_text='Monday opening hour, HH:MM:SS', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='monday_pause_end',
            field=models.TimeField(blank=True, default=datetime.time(15, 0), help_text='Monday end of the Lunchbreak, HH:MM:SS', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='monday_pause_start',
            field=models.TimeField(blank=True, default=datetime.time(13, 0), help_text='Monday start of the Lunchbreak, HH:MM:SS', null=True),
        ),
    ]
