# Generated by Django 5.2.4 on 2025-08-02 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_openings_monday_close_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openings',
            name='friday_close',
            field=models.TimeField(blank=True, default=datetime.time(18, 0), help_text='Friday closing hour, HH:MM:SS', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='friday_open',
            field=models.TimeField(blank=True, default=datetime.time(10, 0), help_text='Friday opening hour, HH:MM:SS', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='friday_pause_end',
            field=models.TimeField(blank=True, default=datetime.time(15, 0), help_text='Friday end of the Lunchbreak, HH:MM:SS', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='friday_pause_start',
            field=models.TimeField(blank=True, default=datetime.time(13, 0), help_text='Friday start of the Lunchbreak, HH:MM:SS', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='saturday_close',
            field=models.TimeField(blank=True, default=datetime.time(18, 0), help_text='Saturday closing hour, HH:MM:SS', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='saturday_open',
            field=models.TimeField(blank=True, default=datetime.time(10, 0), help_text='Saturday opening hour, HH:MM:SS', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='saturday_pause_end',
            field=models.TimeField(blank=True, default=datetime.time(15, 0), help_text='Saturday end of the Lunchbreak, HH:MM:SS', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='saturday_pause_start',
            field=models.TimeField(blank=True, default=datetime.time(13, 0), help_text='Saturday start of the Lunchbreak, HH:MM:SS', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='sunday_close',
            field=models.TimeField(blank=True, default=datetime.time(18, 0), help_text='Sunday closing hour, HH:MM:SS', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='sunday_open',
            field=models.TimeField(blank=True, default=datetime.time(10, 0), help_text='Sunday opening hour, HH:MM:SS', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='sunday_pause_end',
            field=models.TimeField(blank=True, default=datetime.time(15, 0), help_text='Sunday end of the Lunchbreak, HH:MM:SS', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='sunday_pause_start',
            field=models.TimeField(blank=True, default=datetime.time(13, 0), help_text='Sunday start of the Lunchbreak, HH:MM:SS', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='thursday_close',
            field=models.TimeField(blank=True, default=datetime.time(18, 0), help_text='Thursday closing hour, HH:MM:SS', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='thursday_open',
            field=models.TimeField(blank=True, default=datetime.time(10, 0), help_text='Thursday opening hour, HH:MM:SS', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='thursday_pause_end',
            field=models.TimeField(blank=True, default=datetime.time(15, 0), help_text='Thursday end of the Lunchbreak, HH:MM:SS', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='thursday_pause_start',
            field=models.TimeField(blank=True, default=datetime.time(13, 0), help_text='Thursday start of the Lunchbreak, HH:MM:SS', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='tuesday_close',
            field=models.TimeField(blank=True, default=datetime.time(18, 0), help_text='Tuesday closing hour, HH:MM:SS', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='tuesday_open',
            field=models.TimeField(blank=True, default=datetime.time(10, 0), help_text='Tuesday opening hour, HH:MM:SS', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='tuesday_pause_end',
            field=models.TimeField(blank=True, default=datetime.time(15, 0), help_text='Tuesday end of the Lunchbreak, HH:MM:SS', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='tuesday_pause_start',
            field=models.TimeField(blank=True, default=datetime.time(13, 0), help_text='Tuesday start of the Lunchbreak, HH:MM:SS', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='wednesday_close',
            field=models.TimeField(blank=True, default=datetime.time(18, 0), help_text='Wednesday closing hour, HH:MM:SS', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='wednesday_open',
            field=models.TimeField(blank=True, default=datetime.time(10, 0), help_text='Wednesday opening hour, HH:MM:SS', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='wednesday_pause_end',
            field=models.TimeField(blank=True, default=datetime.time(15, 0), help_text='Wednesday end of the Lunchbreak, HH:MM:SS', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='wednesday_pause_start',
            field=models.TimeField(blank=True, default=datetime.time(13, 0), help_text='Wednesday start of the Lunchbreak, HH:MM:SS', null=True),
        ),
    ]
