# Generated by Django 5.2.4 on 2025-08-02 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_openings_friday_close_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massage',
            name='duration',
            field=models.DurationField(default=datetime.time(1, 0), help_text='Duration of the Massage (in HH:MM:SS format)'),
        ),
    ]
