# Generated by Django 5.2.4 on 2025-08-05 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_massage_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'address', 'verbose_name_plural': 'addresses'},
        ),
        migrations.AlterModelOptions(
            name='openings',
            options={'verbose_name': 'opening', 'verbose_name_plural': 'openings'},
        ),
        migrations.AlterModelOptions(
            name='practice',
            options={'verbose_name': 'practice', 'verbose_name_plural': 'practices'},
        ),
        migrations.AddField(
            model_name='massage',
            name='highlighted',
            field=models.BooleanField(default=False, help_text='Different tile background color when listed'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(help_text='City', max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(help_text='Country', max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(help_text='Postal code', max_length=255),
        ),
        migrations.AlterField(
            model_name='massage',
            name='duration',
            field=models.DurationField(default=datetime.time(1, 0), help_text='Duration of the Massage (HH:MM:SS)'),
        ),
        migrations.AlterField(
            model_name='massage',
            name='slug',
            field=models.SlugField(help_text='SEO URL Normalization', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='friday_close',
            field=models.TimeField(blank=True, default=datetime.time(18, 0), help_text='Fermeture (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='friday_open',
            field=models.TimeField(blank=True, default=datetime.time(10, 0), help_text='Ouverture (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='friday_pause_end',
            field=models.TimeField(blank=True, default=datetime.time(15, 0), help_text='Fin de la Pause repas (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='friday_pause_start',
            field=models.TimeField(blank=True, default=datetime.time(13, 0), help_text='Pause repas (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='monday_close',
            field=models.TimeField(blank=True, default=datetime.time(18, 0), help_text='Fermeture (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='monday_open',
            field=models.TimeField(blank=True, default=datetime.time(10, 0), help_text='Ouverture (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='monday_pause_end',
            field=models.TimeField(blank=True, default=datetime.time(15, 0), help_text='Fin de la Pause repas (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='monday_pause_start',
            field=models.TimeField(blank=True, default=datetime.time(13, 0), help_text='Pause repas (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='saturday_close',
            field=models.TimeField(blank=True, default=datetime.time(18, 0), help_text='Fermeture (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='saturday_open',
            field=models.TimeField(blank=True, default=datetime.time(10, 0), help_text='Ouverture (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='saturday_pause_end',
            field=models.TimeField(blank=True, default=datetime.time(15, 0), help_text='Fin de la Pause repas (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='saturday_pause_start',
            field=models.TimeField(blank=True, default=datetime.time(13, 0), help_text='Pause repas (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='sunday_close',
            field=models.TimeField(blank=True, default=datetime.time(18, 0), help_text='Fermeture (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='sunday_open',
            field=models.TimeField(blank=True, default=datetime.time(10, 0), help_text='Ouverture (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='sunday_pause_end',
            field=models.TimeField(blank=True, default=datetime.time(15, 0), help_text='Fin de la Pause repas (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='sunday_pause_start',
            field=models.TimeField(blank=True, default=datetime.time(13, 0), help_text='Pause repas (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='thursday_close',
            field=models.TimeField(blank=True, default=datetime.time(18, 0), help_text='Fermeture (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='thursday_open',
            field=models.TimeField(blank=True, default=datetime.time(10, 0), help_text='Ouverture (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='thursday_pause_end',
            field=models.TimeField(blank=True, default=datetime.time(15, 0), help_text='Fin de la Pause repas (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='thursday_pause_start',
            field=models.TimeField(blank=True, default=datetime.time(13, 0), help_text='Pause repas (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='tuesday_close',
            field=models.TimeField(blank=True, default=datetime.time(18, 0), help_text='Fermeture (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='tuesday_open',
            field=models.TimeField(blank=True, default=datetime.time(10, 0), help_text='Ouverture (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='tuesday_pause_end',
            field=models.TimeField(blank=True, default=datetime.time(15, 0), help_text='Fin de la Pause repas (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='tuesday_pause_start',
            field=models.TimeField(blank=True, default=datetime.time(13, 0), help_text='Pause repas (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='wednesday_close',
            field=models.TimeField(blank=True, default=datetime.time(18, 0), help_text='Fermeture (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='wednesday_open',
            field=models.TimeField(blank=True, default=datetime.time(10, 0), help_text='Ouverture (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='wednesday_pause_end',
            field=models.TimeField(blank=True, default=datetime.time(15, 0), help_text='Fin de la Pause repas (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='wednesday_pause_start',
            field=models.TimeField(blank=True, default=datetime.time(13, 0), help_text='Pause repas (HH:MM:SS)', null=True),
        ),
    ]
