# Generated by Django 5.2.4 on 2025-08-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_address_options_alter_openings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='massage',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
