# Generated by Django 5.2.4 on 2025-08-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_massage_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='massage',
            name='img1',
            field=models.ImageField(blank=True, help_text='A image to illustrate the massage', null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='massage',
            name='img2',
            field=models.ImageField(blank=True, help_text='A image to illustrate the massage', null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='massage',
            name='img3',
            field=models.ImageField(blank=True, help_text='A image to illustrate the massage', null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='massage',
            name='priority',
            field=models.PositiveIntegerField(default=1, help_text='Order index when listing, 1 is first, X last'),
        ),
        migrations.AddField(
            model_name='practice',
            name='cover',
            field=models.ImageField(blank=True, help_text='The cover image used when listed', null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='practice',
            name='img1',
            field=models.ImageField(blank=True, help_text='A image to illustrate the practice', null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='practice',
            name='img2',
            field=models.ImageField(blank=True, help_text='A image to illustrate the practice', null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='practice',
            name='img3',
            field=models.ImageField(blank=True, help_text='A image to illustrate the practice', null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='practice',
            name='img4',
            field=models.ImageField(blank=True, help_text='A image to illustrate the practice', null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='practice',
            name='img5',
            field=models.ImageField(blank=True, help_text='A image to illustrate the practice', null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='massage',
            name='cover',
            field=models.ImageField(blank=True, help_text='The cover image used in tiles when listed. 353*326', null=True, upload_to='img/'),
        ),
    ]
