# Generated by Django 5.2.4 on 2025-08-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_massage_img1_massage_img2_massage_img3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='massage',
            old_name='cover',
            new_name='tcover',
        ),
        migrations.AddField(
            model_name='massage',
            name='tdescription',
            field=models.TextField(blank=True, help_text='The description text under the tile when listed'),
        ),
        migrations.AlterField(
            model_name='massage',
            name='img1',
            field=models.ImageField(blank=True, help_text='An image to illustrate the massage', null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='massage',
            name='img2',
            field=models.ImageField(blank=True, help_text='An image to illustrate the massage', null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='massage',
            name='img3',
            field=models.ImageField(blank=True, help_text='An image to illustrate the massage', null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='img1',
            field=models.ImageField(blank=True, help_text='An image to illustrate the practice', null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='img2',
            field=models.ImageField(blank=True, help_text='An image to illustrate the practice', null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='img3',
            field=models.ImageField(blank=True, help_text='An image to illustrate the practice', null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='img4',
            field=models.ImageField(blank=True, help_text='An image to illustrate the practice', null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='img5',
            field=models.ImageField(blank=True, help_text='An image to illustrate the practice', null=True, upload_to='img/'),
        ),
    ]
