# Generated by Django 5.2.4 on 2025-08-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_cover_massage_tcover_massage_tdescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='massage',
            name='calendly',
            field=models.TextField(blank=True, help_text='Full URL to calendly appointment event'),
        ),
    ]
