# Generated by Django 5.2.4 on 2025-08-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_massage_calendly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='massage',
            name='calendly',
        ),
        migrations.AddField(
            model_name='massage',
            name='calendlyURL',
            field=models.CharField(blank=True, help_text='Full URL to calendly appointment event'),
        ),
    ]
