# Generated by Django 5.2.4 on 2025-08-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_massage_calendly_massage_calendlyurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='massage',
            name='tdescription',
        ),
        migrations.AlterField(
            model_name='massage',
            name='calendlyURL',
            field=models.CharField(blank=True, default='https://calendly.com/reservation-mi-time', help_text='Full URL to calendly appointment event'),
        ),
    ]
