# Generated by Django 5.2.4 on 2025-08-09 19:08

import datetime
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_massage_tdescription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siteconfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='massage',
            name='text1',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='massage',
            name='text2',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='massage',
            name='text3',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='openings',
            name='friday_close',
            field=models.TimeField(blank=True, default=datetime.time(18, 0), help_text='Closing (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='friday_open',
            field=models.TimeField(blank=True, default=datetime.time(10, 0), help_text='Opening (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='friday_pause_end',
            field=models.TimeField(blank=True, default=datetime.time(15, 0), help_text='End of the Lunchbreak (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='friday_pause_start',
            field=models.TimeField(blank=True, default=datetime.time(13, 0), help_text='Lunchbreak (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='monday_close',
            field=models.TimeField(blank=True, default=datetime.time(18, 0), help_text='Closing (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='monday_open',
            field=models.TimeField(blank=True, default=datetime.time(10, 0), help_text='Opening (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='monday_pause_end',
            field=models.TimeField(blank=True, default=datetime.time(15, 0), help_text='End of the Lunchbreak (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='monday_pause_start',
            field=models.TimeField(blank=True, default=datetime.time(13, 0), help_text='Lunchbreak (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='saturday_close',
            field=models.TimeField(blank=True, default=datetime.time(18, 0), help_text='Closing (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='saturday_open',
            field=models.TimeField(blank=True, default=datetime.time(10, 0), help_text='Opening (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='saturday_pause_end',
            field=models.TimeField(blank=True, default=datetime.time(15, 0), help_text='End of the Lunchbreak (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='saturday_pause_start',
            field=models.TimeField(blank=True, default=datetime.time(13, 0), help_text='Lunchbreak (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='sunday_close',
            field=models.TimeField(blank=True, default=datetime.time(18, 0), help_text='Closing (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='sunday_open',
            field=models.TimeField(blank=True, default=datetime.time(10, 0), help_text='Opening (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='sunday_pause_end',
            field=models.TimeField(blank=True, default=datetime.time(15, 0), help_text='End of the Lunchbreak (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='sunday_pause_start',
            field=models.TimeField(blank=True, default=datetime.time(13, 0), help_text='Lunchbreak (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='thursday_close',
            field=models.TimeField(blank=True, default=datetime.time(18, 0), help_text='Closing (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='thursday_open',
            field=models.TimeField(blank=True, default=datetime.time(10, 0), help_text='Opening (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='thursday_pause_end',
            field=models.TimeField(blank=True, default=datetime.time(15, 0), help_text='End of the Lunchbreak (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='thursday_pause_start',
            field=models.TimeField(blank=True, default=datetime.time(13, 0), help_text='Lunchbreak (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='tuesday_close',
            field=models.TimeField(blank=True, default=datetime.time(18, 0), help_text='Closing (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='tuesday_open',
            field=models.TimeField(blank=True, default=datetime.time(10, 0), help_text='Opening (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='tuesday_pause_end',
            field=models.TimeField(blank=True, default=datetime.time(15, 0), help_text='End of the Lunchbreak (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='tuesday_pause_start',
            field=models.TimeField(blank=True, default=datetime.time(13, 0), help_text='Lunchbreak (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='wednesday_close',
            field=models.TimeField(blank=True, default=datetime.time(18, 0), help_text='Closing (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='wednesday_open',
            field=models.TimeField(blank=True, default=datetime.time(10, 0), help_text='Opening (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='wednesday_pause_end',
            field=models.TimeField(blank=True, default=datetime.time(15, 0), help_text='End of the Lunchbreak (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='wednesday_pause_start',
            field=models.TimeField(blank=True, default=datetime.time(13, 0), help_text='Lunchbreak (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='practice',
            name='text1',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='text2',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='practice',
            name='text3',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Text'),
        ),
    ]
