# Generated by Django 5.2.4 on 2025-08-13 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_siteconfig_alter_massage_text1_alter_massage_text2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='place_id',
            field=models.CharField(blank=True, help_text='Place id encoded by google map for this address', max_length=255),
        ),
        migrations.AlterField(
            model_name='openings',
            name='friday_close',
            field=models.TimeField(blank=True, default=datetime.time(18, 0), help_text='Fermeture (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='friday_open',
            field=models.TimeField(blank=True, default=datetime.time(10, 0), help_text='Ouverture (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='friday_pause_end',
            field=models.TimeField(blank=True, default=datetime.time(15, 0), help_text='Fin de la Pause repas (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='friday_pause_start',
            field=models.TimeField(blank=True, default=datetime.time(13, 0), help_text='Pause repas (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='monday_close',
            field=models.TimeField(blank=True, default=datetime.time(18, 0), help_text='Fermeture (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='monday_open',
            field=models.TimeField(blank=True, default=datetime.time(10, 0), help_text='Ouverture (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='monday_pause_end',
            field=models.TimeField(blank=True, default=datetime.time(15, 0), help_text='Fin de la Pause repas (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='monday_pause_start',
            field=models.TimeField(blank=True, default=datetime.time(13, 0), help_text='Pause repas (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='saturday_close',
            field=models.TimeField(blank=True, default=datetime.time(18, 0), help_text='Fermeture (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='saturday_open',
            field=models.TimeField(blank=True, default=datetime.time(10, 0), help_text='Ouverture (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='saturday_pause_end',
            field=models.TimeField(blank=True, default=datetime.time(15, 0), help_text='Fin de la Pause repas (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='saturday_pause_start',
            field=models.TimeField(blank=True, default=datetime.time(13, 0), help_text='Pause repas (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='sunday_close',
            field=models.TimeField(blank=True, default=datetime.time(18, 0), help_text='Fermeture (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='sunday_open',
            field=models.TimeField(blank=True, default=datetime.time(10, 0), help_text='Ouverture (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='sunday_pause_end',
            field=models.TimeField(blank=True, default=datetime.time(15, 0), help_text='Fin de la Pause repas (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='sunday_pause_start',
            field=models.TimeField(blank=True, default=datetime.time(13, 0), help_text='Pause repas (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='thursday_close',
            field=models.TimeField(blank=True, default=datetime.time(18, 0), help_text='Fermeture (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='thursday_open',
            field=models.TimeField(blank=True, default=datetime.time(10, 0), help_text='Ouverture (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='thursday_pause_end',
            field=models.TimeField(blank=True, default=datetime.time(15, 0), help_text='Fin de la Pause repas (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='thursday_pause_start',
            field=models.TimeField(blank=True, default=datetime.time(13, 0), help_text='Pause repas (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='tuesday_close',
            field=models.TimeField(blank=True, default=datetime.time(18, 0), help_text='Fermeture (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='tuesday_open',
            field=models.TimeField(blank=True, default=datetime.time(10, 0), help_text='Ouverture (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='tuesday_pause_end',
            field=models.TimeField(blank=True, default=datetime.time(15, 0), help_text='Fin de la Pause repas (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='tuesday_pause_start',
            field=models.TimeField(blank=True, default=datetime.time(13, 0), help_text='Pause repas (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='wednesday_close',
            field=models.TimeField(blank=True, default=datetime.time(18, 0), help_text='Fermeture (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='wednesday_open',
            field=models.TimeField(blank=True, default=datetime.time(10, 0), help_text='Ouverture (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='wednesday_pause_end',
            field=models.TimeField(blank=True, default=datetime.time(15, 0), help_text='Fin de la Pause repas (HH:MM:SS)', null=True),
        ),
        migrations.AlterField(
            model_name='openings',
            name='wednesday_pause_start',
            field=models.TimeField(blank=True, default=datetime.time(13, 0), help_text='Pause repas (HH:MM:SS)', null=True),
        ),
    ]
