# Generated by Django 5.2.4 on 2025-08-14 18:59

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_address_place_id_alter_openings_friday_close_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('site_email', models.CharField(blank=True, help_text='Email for contacts forms', max_length=255)),
                ('header_mobile', models.CharField(blank=True, help_text='Mobile number in header', max_length=255)),
                ('header_openings', models.CharField(blank=True, help_text='Oopening time text in header', max_length=255)),
                ('fb', models.CharField(blank=True, help_text='Facebook Account', max_length=255)),
                ('instagram', models.CharField(blank=True, help_text='Instagram Account', max_length=255)),
                ('copyright', models.CharField(blank=True, help_text='Copyright content in the footer', max_length=255)),
            ],
            options={
                'verbose_name': 'Global Site Config',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Content of the page', verbose_name='Text')),
                ('slug', models.SlugField(help_text='SEO Url Normalization', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
        migrations.DeleteModel(
            name='Siteconfig',
        ),
    ]
