# Generated by Django 5.2.4 on 2025-08-14 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_globalconfig_page_delete_siteconfig'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GlobalConfig',
            new_name='SiteConfig',
        ),
    ]
