# Generated by Django 5.2.4 on 2025-08-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_globalconfig_siteconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='massage',
            name='meta_Keywords',
            field=models.CharField(blank=True, help_text='SEO Meta Keyword (max 10)', max_length=255),
        ),
        migrations.AddField(
            model_name='massage',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO Meta Description (90->160)', max_length=255),
        ),
        migrations.AddField(
            model_name='massage',
            name='meta_title',
            field=models.CharField(default='Default', help_text='SEO Meta Title (50->70)', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='meta_Keywords',
            field=models.CharField(blank=True, help_text='SEO Meta Keyword (max 10)', max_length=255),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO Meta Description (90->160)', max_length=255),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_title',
            field=models.CharField(default='Default', help_text='SEO Meta Title (50->70)', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practice',
            name='meta_Keywords',
            field=models.CharField(blank=True, help_text='SEO Meta Keyword (max 10)', max_length=255),
        ),
        migrations.AddField(
            model_name='practice',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO Meta Description (90->160)', max_length=255),
        ),
        migrations.AddField(
            model_name='practice',
            name='meta_title',
            field=models.CharField(default='Default', help_text='SEO Meta Title (50->70)', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='design',
            field=models.CharField(blank=True, help_text='Design credit content in the footer', max_length=255),
        ),
    ]
