# Generated by Django 5.2.4 on 2025-08-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_massage_meta_keywords_massage_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massage',
            name='meta_description',
            field=models.CharField(help_text='SEO Meta Description (90->160)', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='massage',
            name='meta_title',
            field=models.CharField(help_text='SEO Meta Title (50->70)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_description',
            field=models.CharField(help_text='SEO Meta Description (90->160)', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_title',
            field=models.CharField(help_text='SEO Meta Title (50->70)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='practice',
            name='meta_description',
            field=models.CharField(help_text='SEO Meta Description (90->160)', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='practice',
            name='meta_title',
            field=models.CharField(help_text='SEO Meta Title (50->70)', max_length=100, unique=True),
        ),
    ]
