# Generated by Django 5.2.4 on 2025-08-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_massage_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='massage',
            name='img1_alt',
            field=models.CharField(blank=True, help_text='SEO Img Alt', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='massage',
            name='img2_alt',
            field=models.CharField(blank=True, help_text='SEO Img Alt', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='massage',
            name='img3_alt',
            field=models.CharField(blank=True, help_text='SEO Img Alt', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='practice',
            name='img1_alt',
            field=models.CharField(blank=True, help_text='SEO Img Alt', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='practice',
            name='img2_alt',
            field=models.CharField(blank=True, help_text='SEO Img Alt', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='practice',
            name='img3_alt',
            field=models.CharField(blank=True, help_text='SEO Img Alt', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='practice',
            name='img4_alt',
            field=models.CharField(blank=True, help_text='SEO Img Alt', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='practice',
            name='img5_alt',
            field=models.CharField(blank=True, help_text='SEO Img Alt', max_length=255, null=True),
        ),
    ]
