# Generated by Django 5.2.4 on 2025-08-16 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_massage_img1_alt_massage_img2_alt_massage_img3_alt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteconfig',
            old_name='fb',
            new_name='facebook',
        ),
    ]
