# Generated by Django 5.2.4 on 2025-08-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_rename_fb_siteconfig_facebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_home',
            field=models.BooleanField(default=False, help_text='Is it the homepage ? (only 1 should be)'),
        ),
    ]
