# Generated by Django 5.2.4 on 2025-08-16 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_page_is_home'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='meta_Keywords',
            new_name='meta_keywords',
        ),
    ]
