# Generated by Django 5.2.4 on 2025-08-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_rename_meta_keywords_page_meta_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='is_home',
        ),
        migrations.AddField(
            model_name='page',
            name='custom_view',
            field=models.CharField(help_text='Link custom view to its meta datas', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='massage',
            name='meta_Keywords',
            field=models.CharField(help_text='SEO Meta Keyword (max 10)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_keywords',
            field=models.CharField(help_text='SEO Meta Keyword (max 10)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='practice',
            name='meta_Keywords',
            field=models.CharField(help_text='SEO Meta Keyword (max 10)', max_length=255, null=True),
        ),
    ]
