# Generated by Django 5.2.4 on 2025-08-16 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_page_is_home_page_custom_view_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='custom_view',
            new_name='custom_viewname',
        ),
    ]
