# Generated by Django 5.2.4 on 2025-08-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_rename_custom_view_page_custom_viewname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='custom_viewname',
            field=models.CharField(blank=True, help_text='Link custom view to its meta datas', max_length=100, null=True),
        ),
    ]
