# Generated by Django 5.2.4 on 2025-08-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_page_custom_viewname'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='menu_position',
            field=models.SmallIntegerField(blank=True, help_text="Position of the item in the menu (empties won't be displayed)", null=True),
        ),
    ]
