# Generated by Django 5.2.4 on 2025-08-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_page_menu_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='massage',
            name='tcover',
        ),
        migrations.AddField(
            model_name='massage',
            name='cover',
            field=models.ImageField(blank=True, help_text='The cover image used in tiles when listed.', null=True, upload_to='img/'),
        ),
    ]
