# Generated by Django 5.2.4 on 2025-08-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_massage_tcover_massage_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='placeholder_img',
            field=models.ImageField(blank=True, help_text='An Image displayed when the original is not found', null=True, upload_to='img/'),
        ),
    ]
