# Generated by Django 5.2.4 on 2025-08-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_siteconfig_placeholder_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='robots_content',
            field=models.TextField(blank=True, help_text='Content of robots.txt'),
        ),
    ]
