# Generated by Django 5.2.4 on 2025-08-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_siteconfig_robots_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='massage',
            name='text2',
        ),
        migrations.RemoveField(
            model_name='massage',
            name='text3',
        ),
        migrations.AddField(
            model_name='massage',
            name='tile_label',
            field=models.CharField(blank=True, help_text='Label displayed on the tile for list view.', max_length=100, null=True),
        ),
    ]
