# Generated by Django 5.2.4 on 2025-08-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_massage_text2_remove_massage_text3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practice',
            name='text2',
        ),
        migrations.RemoveField(
            model_name='practice',
            name='text3',
        ),
        migrations.AddField(
            model_name='page',
            name='footer_position',
            field=models.SmallIntegerField(blank=True, help_text="Position of the item in footer links section (empties won't be displayed)", null=True),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='header_openings',
            field=models.CharField(blank=True, help_text='Opening time text in header', max_length=255),
        ),
    ]
