# Generated by Django 5.2.4 on 2025-08-30 17:42

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_practice_text2_remove_practice_text3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='footer_about_text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Content of the about block in footer', verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='footer_about_title',
            field=models.CharField(blank=True, default='Mireille', help_text='Title of the about block in footer', max_length=100),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='header_mobile',
            field=models.CharField(blank=True, help_text='Main Mobile number visible on the website', max_length=255),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='site_email',
            field=models.CharField(blank=True, help_text='Email visible on the website', max_length=255),
        ),
    ]
