# Generated by Django 5.2.4 on 2025-09-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_siteconfig_footer_about_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='meta_robots',
            field=models.CharField(help_text='SEO Meta Robots', max_length=255, null=True),
        ),
    ]
