# Generated by Django 5.2.4 on 2025-09-03 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_page_meta_robots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='SEO Meta Keyword (max 10)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_robots',
            field=models.CharField(blank=True, help_text='SEO Meta Robots', max_length=255, null=True),
        ),
    ]
