# Generated by Django 5.2.4 on 2025-09-04 20:24

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_page_meta_keywords_alter_page_meta_robots'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text='SEO URL Normalization', max_length=100, unique=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('edit_date', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(help_text='SEO Meta Title (50->70)', max_length=100, unique=True)),
                ('meta_description', models.CharField(help_text='SEO Meta Description (90->160)', max_length=255, unique=True)),
                ('meta_Keywords', models.CharField(help_text='SEO Meta Keyword (max 10)', max_length=255, null=True)),
                ('stripe_product_id', models.CharField(blank=True, help_text='Stripe Price id of the product', max_length=100, null=True)),
                ('stripe_price_id', models.CharField(blank=True, help_text='Stripe Price id of the product', max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the product', max_digits=7)),
                ('tile_label', models.CharField(blank=True, help_text='Label displayed on the tile for list view.', max_length=100, null=True)),
                ('cover', models.ImageField(blank=True, help_text='The cover image used in tiles when listed.', null=True, upload_to='img/')),
                ('priority', models.PositiveIntegerField(default=1, help_text='Order index when listing, 1 is first, X last')),
                ('highlighted', models.BooleanField(default=False, help_text='Different tile background color when listed')),
                ('text1', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('img1', models.ImageField(blank=True, help_text='An image to illustrate the massage', null=True, upload_to='img/')),
                ('img1_alt', models.CharField(blank=True, help_text='SEO Img Alt', max_length=255, null=True)),
                ('img2', models.ImageField(blank=True, help_text='An image to illustrate the massage', null=True, upload_to='img/')),
                ('img2_alt', models.CharField(blank=True, help_text='SEO Img Alt', max_length=255, null=True)),
                ('img3', models.ImageField(blank=True, help_text='An image to illustrate the massage', null=True, upload_to='img/')),
                ('img3_alt', models.CharField(blank=True, help_text='SEO Img Alt', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Product',
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='massage',
            options={'verbose_name': 'Product'},
        ),
        migrations.AddField(
            model_name='massage',
            name='stripe_price_id',
            field=models.CharField(blank=True, help_text='Stripe Price id of the product', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='massage',
            name='stripe_product_id',
            field=models.CharField(blank=True, help_text='Stripe Price id of the product', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='massage',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price of the product', max_digits=7),
        ),
    ]
