# Generated by Django 5.2.4 on 2025-09-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_giftcard_alter_massage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='giftcard',
            options={'verbose_name': 'Gift card', 'verbose_name_plural': 'Gift Cards'},
        ),
        migrations.AlterModelOptions(
            name='massage',
            options={'verbose_name': 'Massage', 'verbose_name_plural': 'Massages'},
        ),
        migrations.AddField(
            model_name='giftcard',
            name='stripe_coupon_id',
            field=models.CharField(blank=True, help_text='Stripe Coupon id of the gift card', max_length=100, null=True),
        ),
    ]
