# Generated by Django 5.2.4 on 2025-09-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_giftcard_options_alter_massage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='gift_label',
            field=models.CharField(blank=True, help_text='Gift name on the giftcard', max_length=100, null=True),
        ),
    ]
