# Generated by Django 5.2.4 on 2025-09-06 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_giftcard_gift_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600), help_text='Duration of the gifted Massage (HH:MM:SS)'),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='stripe_product_id',
            field=models.CharField(blank=True, help_text='Stripe Product id of the product', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='massage',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600), help_text='Duration of the Massage (HH:MM:SS)'),
        ),
        migrations.AlterField(
            model_name='massage',
            name='stripe_product_id',
            field=models.CharField(blank=True, help_text='Stripe Product id of the product', max_length=100, null=True),
        ),
    ]
