# Generated by Django 5.2.4 on 2025-09-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_giftcard_duration_alter_giftcard_stripe_product_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='openings',
            options={'verbose_name': 'Opening', 'verbose_name_plural': 'Openings'},
        ),
        migrations.AlterModelOptions(
            name='practice',
            options={'verbose_name': 'Practice', 'verbose_name_plural': 'Practices'},
        ),
        migrations.AlterModelOptions(
            name='siteconfig',
            options={'verbose_name': 'Global Site Config', 'verbose_name_plural': 'Global Site Configs'},
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='gift_label',
            field=models.CharField(default='Carte Cadeau', help_text='Gift label on the giftcard', max_length=100),
        ),
    ]
