# Generated by Django 5.2.4 on 2025-09-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_address_options_alter_openings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcard',
            name='gift_label',
            field=models.CharField(help_text='Gift label on the giftcard', max_length=100),
        ),
    ]
