# Generated by Django 5.2.4 on 2025-09-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_giftcard_gift_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(blank=True, help_text='SEO Url Normalization', max_length=100, null=True, unique=True),
        ),
    ]
