# Generated by Django 5.2.4 on 2025-09-08 19:30

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_page_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='content',
            new_name='text',
        ),
        migrations.AddField(
            model_name='page',
            name='text2',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Additionnal content of the page', verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='page',
            name='text3',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Additionnal content of the page', verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='practice',
            name='text2',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Additionnal content of the page', verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='practice',
            name='text3',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Additionnal content of the page', verbose_name='Text'),
        ),
    ]
