# Generated by Django 5.2.4 on 2025-09-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_rename_content_page_text_page_text2_page_text3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='legal_page',
            field=models.BooleanField(default=False, help_text='Page legaly required ? (displayed under the footer)'),
        ),
    ]
