# Generated by Django 5.2.4 on 2025-12-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_bundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='promo_discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discounted price of the product', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='bundle',
            name='promo_end_date',
            field=models.DateTimeField(blank=True, help_text='When the promotion end', null=True),
        ),
        migrations.AddField(
            model_name='bundle',
            name='promo_start_date',
            field=models.DateTimeField(blank=True, help_text='When the promotion begin', null=True),
        ),
        migrations.AddField(
            model_name='bundle',
            name='promo_stripe_coupon_id',
            field=models.CharField(blank=True, help_text='Apply a coupon code to the product checkout, used for recurrent promo', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='promo_discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discounted price of the product', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='promo_end_date',
            field=models.DateTimeField(blank=True, help_text='When the promotion end', null=True),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='promo_start_date',
            field=models.DateTimeField(blank=True, help_text='When the promotion begin', null=True),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='promo_stripe_coupon_id',
            field=models.CharField(blank=True, help_text='Apply a coupon code to the product checkout, used for recurrent promo', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='massage',
            name='promo_discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discounted price of the product', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='massage',
            name='promo_end_date',
            field=models.DateTimeField(blank=True, help_text='When the promotion end', null=True),
        ),
        migrations.AddField(
            model_name='massage',
            name='promo_start_date',
            field=models.DateTimeField(blank=True, help_text='When the promotion begin', null=True),
        ),
        migrations.AddField(
            model_name='massage',
            name='promo_stripe_coupon_id',
            field=models.CharField(blank=True, help_text='Apply a coupon code to the product checkout, used for recurrent promo', max_length=100, null=True),
        ),
    ]
