# Generated by Django 5.2.4 on 2025-12-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_bundle_promo_discounted_price_bundle_promo_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='promo_name',
            field=models.CharField(blank=True, help_text='Name of the promo displayed on full view', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='promo_name',
            field=models.CharField(blank=True, help_text='Name of the promo displayed on full view', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='massage',
            name='promo_name',
            field=models.CharField(blank=True, help_text='Name of the promo displayed on full view', max_length=100, null=True),
        ),
    ]
