# Generated by Django 5.2.4 on 2026-02-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_bundle_promo_name_giftcard_promo_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='publication_state',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('HIDDEN', 'Hidden'), ('PUBLISHED', 'Published')], default='DRAFT', help_text='Current state of the product (draft,hidden,published)'),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='publication_state',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('HIDDEN', 'Hidden'), ('PUBLISHED', 'Published')], default='DRAFT', help_text='Current state of the product (draft,hidden,published)'),
        ),
        migrations.AddField(
            model_name='massage',
            name='publication_state',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('HIDDEN', 'Hidden'), ('PUBLISHED', 'Published')], default='DRAFT', help_text='Current state of the product (draft,hidden,published)'),
        ),
    ]
